#!/usr/bin/env bash

# To check if the required number of parameters is passed
if [ "$#" -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]; then
    scp -o StrictKeyChecking=no "$1" "$3"@"$2":~/
else
    scp -i "$4" -o StrictKeyChecking=no "$1" "$3"@"$2":~/
fi
