#!/usr/bin/env bash
#script to install and configure HAProxy on lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy

#configure load balancer to send traffic to web-01 and web-02 servers
#distribute request between servers using roundrobin algorithm
server_config=\
"
frontend alxmichael-frontend
        bind *:80
        mode http
        default_backend alxmichael-backend
backend alxmichael-backend
        balance roundrobin
        server 163985-web-01 100.25.38.204:80 check
        server 163985-web-02 54.84.172.189:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

#ensure lb can be managed via init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
