#!/usr/bin/env bash
# debugging nginx port 80
# delete existing /etc/nginx/sites-available/default and replace it
# symbolic link.
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
