#!/usr/bin/env bash
# displays "To infinity and beyond" indefinitely.
#+ In between each iteration of the loop, add a sleep 2
# displays "I am invincible!!!" in between each iteration.

trap 'echo " I am invincible!!!"' SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
