#!/usr/bin/env bash
# Gracefully reloads Gunicorn

# Find the Gunicorn master process IDs
gunicorn_masters="$(ps aux | awk '/Ss/ && /gunicorn/ {print $2}' | head -n -1 | tr '\n' ' ')"

# Check if there are Gunicorn master processes
if [ -n "$gunicorn_masters" ]; then
    for master_pid in $gunicorn_masters; do

        # Send HUP signal to gracefully reload Gunicorn
        kill -HUP "$master_pid"
    done
fi
